### ISSUE TITLE
1.9.4-1.7.0 crashes dedicated 1.9 forge server.

### ISSUE THREAD

**Issue by kreezxil** [shadowfacts/YeOldeTanks#17]
You tagged it as being compatible with 1.9.0 as well as 1.9.4, this is the fourth mod I've found like this, seems with 1.9.4 when you compile them for for that tier, they for w/e reason refuse to be backwards compat with with some other tier.

```
[17:04:21] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraftforge.fml.common.WrongMinecraftVersionException: Wrong Minecraft version for YeOldeTanks
Wrong Minecraft Versions!
Mod: YeOldeTanks
Location: /root/extreme_19/mods/ye-olde-tanks-1.9.x-1.7.0.jar
Expected: [1.9.4,1.9.4]
Current: Minecraft 1.9


        at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:232) ~[Loader.class:?]
        at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:502) ~[Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:92) ~[FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:320) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:119) ~[la.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]

```

**Comment by shadowfacts** [comment]
Whoops, fixed that. Use 1.6.0 for Minecraft 1.9.
